package com.asuis.j2ee.model;

public class RoleRoutes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_routes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_routes.routes_id
     *
     * @mbg.generated
     */
    private Integer routesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_routes.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_routes.id
     *
     * @return the value of role_routes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_routes.id
     *
     * @param id the value for role_routes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_routes.routes_id
     *
     * @return the value of role_routes.routes_id
     *
     * @mbg.generated
     */
    public Integer getRoutesId() {
        return routesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_routes.routes_id
     *
     * @param routesId the value for role_routes.routes_id
     *
     * @mbg.generated
     */
    public void setRoutesId(Integer routesId) {
        this.routesId = routesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_routes.role_id
     *
     * @return the value of role_routes.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_routes.role_id
     *
     * @param roleId the value for role_routes.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}