package com.asuis.j2ee.model;

public class Routes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.web_pata
     *
     * @mbg.generated
     */
    private String webPata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column routes.extra
     *
     * @mbg.generated
     */
    private String extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.id
     *
     * @return the value of routes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.id
     *
     * @param id the value for routes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.pid
     *
     * @return the value of routes.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.pid
     *
     * @param pid the value for routes.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.path
     *
     * @return the value of routes.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.path
     *
     * @param path the value for routes.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.web_pata
     *
     * @return the value of routes.web_pata
     *
     * @mbg.generated
     */
    public String getWebPata() {
        return webPata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.web_pata
     *
     * @param webPata the value for routes.web_pata
     *
     * @mbg.generated
     */
    public void setWebPata(String webPata) {
        this.webPata = webPata == null ? null : webPata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.desc
     *
     * @return the value of routes.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.desc
     *
     * @param desc the value for routes.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.sort
     *
     * @return the value of routes.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.sort
     *
     * @param sort the value for routes.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column routes.extra
     *
     * @return the value of routes.extra
     *
     * @mbg.generated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column routes.extra
     *
     * @param extra the value for routes.extra
     *
     * @mbg.generated
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }
}