package com.asuis.j2ee.model;

public class UsersAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_auth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_auth.indentity
     *
     * @mbg.generated
     */
    private String indentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_auth.identifier
     *
     * @mbg.generated
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_auth.credential
     *
     * @mbg.generated
     */
    private String credential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_auth.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_auth.id
     *
     * @return the value of users_auth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_auth.id
     *
     * @param id the value for users_auth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_auth.indentity
     *
     * @return the value of users_auth.indentity
     *
     * @mbg.generated
     */
    public String getIndentity() {
        return indentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_auth.indentity
     *
     * @param indentity the value for users_auth.indentity
     *
     * @mbg.generated
     */
    public void setIndentity(String indentity) {
        this.indentity = indentity == null ? null : indentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_auth.identifier
     *
     * @return the value of users_auth.identifier
     *
     * @mbg.generated
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_auth.identifier
     *
     * @param identifier the value for users_auth.identifier
     *
     * @mbg.generated
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_auth.credential
     *
     * @return the value of users_auth.credential
     *
     * @mbg.generated
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_auth.credential
     *
     * @param credential the value for users_auth.credential
     *
     * @mbg.generated
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_auth.user_id
     *
     * @return the value of users_auth.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_auth.user_id
     *
     * @param userId the value for users_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}