package com.asuis.j2ee.model;

public class UserDep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dep.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dep.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dep.dep_id
     *
     * @mbg.generated
     */
    private Integer depId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dep.id
     *
     * @return the value of user_dep.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dep.id
     *
     * @param id the value for user_dep.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dep.user_id
     *
     * @return the value of user_dep.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dep.user_id
     *
     * @param userId the value for user_dep.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dep.dep_id
     *
     * @return the value of user_dep.dep_id
     *
     * @mbg.generated
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dep.dep_id
     *
     * @param depId the value for user_dep.dep_id
     *
     * @mbg.generated
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }
}