package com.asuis.j2ee.dao;

import com.asuis.j2ee.model.RoleRoutes;

public interface RoleRoutesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    int insert(RoleRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    int insertSelective(RoleRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    RoleRoutes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleRoutes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_routes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleRoutes record);
}