package com.asuis.j2ee.dao;

import com.asuis.j2ee.model.UserDep;

public interface UserDepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    int insert(UserDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    int insertSelective(UserDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    UserDep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dep
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDep record);
}